"""initial

Revision ID: 31e9909811d4
Revises: 
Create Date: 2024-03-28 13:12:14.995573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31e9909811d4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('current_indication', sa.Float(), nullable=False),
    sa.Column('previous_indication', sa.Float(), nullable=True),
    sa.Column('implementer', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('EXECUTING', 'CHECKING', 'COMPLETED', 'OVERDUE', name='statusstate'), nullable=False),
    sa.Column('near_photo_url', sa.String(), nullable=True),
    sa.Column('far_photo_url', sa.String(), nullable=True),
    sa.Column('completion_date', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('task_id', name=op.f('pk_tasks'))
    )
    op.create_table('users',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('middle_name', sa.String(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('photo_url', sa.String(), server_default=sa.text('NULL'), nullable=True),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), server_default=sa.text('NULL'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_users')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('tasks')
    # ### end Alembic commands ###
