[api]
host = "localhost"
port = 5000
debug = true

[db]
host = "localhost"
port = 5432
database = "test"
user = "postgres"
password = "2685118"
echo = true

[storage]
access_key ="YCAJEzExiV55ARCpSqLAdhBW5"
secret_key = "YCNbyHM9iHRMVA1k8mmfiLGp5KiCOeXaeyGAYGBL"
endpoint_url = "https://storage.yandexcloud.net"
region_name = "ru-central1"
bucket = "2aobjectstorage"

[logging]
level = "DEBUG"
render_json_logs = false
#path = "./logs/logs.log"